PACKAGE:
  NAME: satellighte
  ARCH: archs
  MODEL: models

MODEL:
  mobilenetv2:
    default:
      eurosat:
        v0:
          url: "https://drive.google.com/file/d/1EP3YBmJZkeLhg4KaCsQSAHVaaZusPurz"
